# Generated by Django 3.2 on 2021-05-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Daneuzytkownikow',
            fields=[
                ('iduzytkownika', models.AutoField(db_column='IdUzytkownika', primary_key=True, serialize=False)),
                ('plec', models.PositiveIntegerField()),
                ('wiek', models.PositiveIntegerField()),
                ('ulica', models.CharField(max_length=45)),
                ('numerbudynku', models.PositiveIntegerField(db_column='numerBudynku')),
                ('numermieszkania', models.PositiveIntegerField(blank=True, db_column='numerMieszkania', null=True)),
                ('miasto', models.CharField(max_length=45)),
                ('kodpocztowy', models.CharField(db_column='kodPocztowy', max_length=45)),
                ('nip', models.PositiveBigIntegerField(blank=True, db_column='NIP', null=True)),
            ],
            options={
                'db_table': 'daneuzytkownikow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Danezamowien',
            fields=[
                ('iddanezamowien', models.AutoField(primary_key=True, serialize=False)),
                ('iduzytkownika', models.CharField(db_column='idUzytkownika', max_length=45)),
                ('idkoszyka', models.PositiveIntegerField(db_column='idKoszyka')),
                ('numerbudynku', models.PositiveIntegerField(db_column='numerBudynku')),
                ('numermieszkania', models.PositiveIntegerField(blank=True, db_column='numerMieszkania', null=True)),
                ('kodpocztowy', models.CharField(db_column='kodPocztowy', max_length=45)),
                ('miasto', models.CharField(max_length=45)),
                ('sposobplatnosci', models.PositiveIntegerField(db_column='sposobPlatnosci')),
                ('statusrealizacji', models.PositiveIntegerField(db_column='statusRealizacji')),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'danezamowien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('idkategoria', models.AutoField(db_column='idKategoria', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=45)),
                ('kategoria', models.CharField(db_column='Kategoria', max_length=45)),
            ],
            options={
                'db_table': 'kategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('idtab', models.AutoField(db_column='idTab', primary_key=True, serialize=False)),
                ('idkoszyk', models.PositiveIntegerField(db_column='idKoszyk')),
                ('idproduktow', models.PositiveIntegerField(db_column='idProduktow')),
                ('ilosc', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'koszyk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liczbasztuk',
            fields=[
                ('idliczbasztuk', models.AutoField(primary_key=True, serialize=False)),
                ('idproduktu', models.PositiveIntegerField(db_column='idProduktu', unique=True)),
                ('ilosc', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'liczbasztuk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('idprodukty', models.AutoField(db_column='idProdukty', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=45)),
                ('opis', models.TextField()),
                ('zdjecie', models.CharField(max_length=500)),
                ('netto', models.FloatField()),
                ('brutto', models.FloatField(blank=True, null=True)),
                ('podatek', models.FloatField()),
                ('kategoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'produkty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rabaty',
            fields=[
                ('idrabaty', models.AutoField(db_column='idRabaty', primary_key=True, serialize=False)),
                ('iduzytkownika', models.PositiveIntegerField(db_column='idUzytkownika')),
                ('wartoscrabatu', models.FloatField(blank=True, db_column='wartoscRabatu', null=True)),
            ],
            options={
                'db_table': 'rabaty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('iduzytkownicy', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('haslo', models.CharField(blank=True, max_length=45, null=True)),
                ('iduzytkownika', models.PositiveIntegerField(blank=True, db_column='idUzytkownika', null=True, unique=True)),
                ('statuskonta', models.PositiveIntegerField(blank=True, db_column='statusKonta', null=True)),
            ],
            options={
                'db_table': 'uzytkownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('idzamowienia', models.AutoField(db_column='idZamowienia', primary_key=True, serialize=False)),
                ('iduzytkownika', models.PositiveIntegerField(db_column='idUzytkownika')),
            ],
            options={
                'db_table': 'zamowienia',
                'managed': False,
            },
        ),
    ]
